#!/usr/bin/env bash
name="xorgproto"
version="2023.2"
description="X.Org combined protocol headers"
source="https://www.x.org/releases/individual/proto/xorgproto-${version}.tar.xz"
depends=""
group="x11.base"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        --datadir=/usr/lib \
		-Dlegacy=true \
		-Ddefault_library=both
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}