#!/usr/bin/env bash
name="rust"
version="1.76.0"
url="https://www.rust-lang.org"
description="Systems programming language from Mozilla"
source="https://static.rust-lang.org/dist/rustc-$version-src.tar.gz"   
depends="curl,gcc,libssh,llvm"
makedepends="cmake,ninja,perl,python"
group="dev.lang"
# disable strip
dontstrip=1



setup () {
cd $SOURCEDIR
cp -prfv $PACKAGEDIR/config.toml  $SOURCEDIR/config.toml

}

build () {
    python3 ./x.py build -j `nproc`
}

package () {
    python3 ./x.py install -j `nproc`
}

